Сделал рефакторинг проекта согласно принципам SOLID и 3 кейсам, котор…
pazhik/Java_bit_hometask pull request #2
Opened 2021-03-10 16:54 UTC by pazhik

…ые должны вести к изменению проекта (описанные в ReadMe в изначальном репозитории)

2021-03-12 14:28 UTC, a-ivanov requested changes

2021-03-12 14:28 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventHandler.java
> +    private SensorEvent getNextSensorEvent() {
Нарушение SRP, перенесите логику в отдельный класс (с интерфейсом).

2021-03-12 14:28 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventHandler.java
> +            if (event.getType() == DOOR_OPEN || event.getType() == DOOR_CLOSED) {
Нарушение OCP, создайте отдельные классы - обработчики.

2021-03-12 14:28 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/AllLightOffEvent.java
> +    private void sendCommand(SensorCommand command) {
Нарушение SRP, перенесите в отдельный класс (с интерфейсом).

2021-03-12 14:28 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/DoorEvents.java
> +                        if (room.getName().equals("hall")) {
Сценарий - в отдельном обработчике.

2021-03-16 13:43 UTC, pazhik commented on src/main/java/ru/sbt/mipt/oop/DoorEvents.java
> +                        if (room.getName().equals("hall")) {
Я не понимаю, что вы от меня хотите в данном коде :( Внести эту проверку в closeDoor?

2021-03-16 15:00 UTC, pazhik commented on src/main/java/ru/sbt/mipt/oop/DoorEvents.java
> +                        if (room.getName().equals("hall")) {
А, я нашел ответ на свой вопрос в чате от вас же) спасибо.

2021-03-17 06:07 UTC, a-ivanov requested changes

2021-03-17 06:07 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventHandler.java
> +        EventFactory eventCreator = new SensorEventFactory();
DIP: создавайте в `main`, передавайте сюда через конструктор.

2021-03-17 06:07 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventHandler.java
> +            new LightEventsHandler(event, smartHome);
DIP, исправьте.

2021-03-17 06:07 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventHandler.java
> +            new DoorEventsHandler(event, smartHome);
DIP, исправьте.

2021-03-17 06:07 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/HallDoorEvent.java
> +public class HallDoorEvent {
Этот скорее не событие, это набор утилит для работы с ними. Переименуйте во что-то типа `HallDoorEventUtils`.

2021-03-17 06:07 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/DoorEvents.java
> +    public void handleEvent() {
См. комментарий к `HallDoorEvent`. Но мне кажется, что эту логику можно перенести в обработчик.

2021-03-17 06:07 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SensorCommandFactory.java
> +public class SensorCommandFactory implements CommandFactory {
Это скорее `CommandSender`.

2021-03-17 06:07 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/HallDoorEventHandler.java
> +public class HallDoorEventHandler {
Этот класс используется?

2021-03-18 06:57 UTC, pazhik commented on src/main/java/ru/sbt/mipt/oop/HallDoorEventHandler.java
> +public class HallDoorEventHandler {
да, для обработки случая когда закрывается входная дверь, и я поместил его вызов в обработчик события дверей, как особый случай

2021-03-25 06:23 UTC, pazhik commented on src/main/java/ru/sbt/mipt/oop/DoorEvents.java
> +    public void handleEvent() {
Перенес всю логику в DoorEventHandler и удалил Door Events

2021-03-25 06:29 UTC, pazhik commented on src/main/java/ru/sbt/mipt/oop/HallDoorEventHandler.java
> +public class HallDoorEventHandler {
Но я перенес всю логику в обработчик события и удалил этот класс

2021-03-29 05:27 UTC, a-ivanov requested changes
Перечитайте замечания и исправьте.

2021-03-31 06:36 UTC, pazhik commented on src/main/java/ru/sbt/mipt/oop/EventHandler.java
> +        EventFactory eventCreator = new SensorEventFactory();
Вынес в main

2021-04-01 05:19 UTC, a-ivanov reviewed
1 и 2 дз зачту. Про 3 непонятно: не вижу декоратора, хотя есть класс сигнализации с состояниями.

2021-04-01 05:19 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/HallDoorEventHandler.java
> +                CommandFactory commandFactory = new CommandSender();
DIP, передавайте через конструктор.

2021-04-28 08:42 UTC, closed without merging